### PR TITLE
Git week1

### PR DESCRIPTION
**Pull request by andrii1**

### CODE REVIEW

**Review by marta-ov — CHANGES_REQUESTED** [review]
Great work Andrii! :D

I have one more task for you, can you add another country name to countries.txt, add, commit, and push please? You'll see that the new commit shows up in the PR right away :) 
This is to mimic the process of giving/implementing feedback :)

**Comment by andrii1** [comment]
> Great work Andrii! :D
> 
> I have one more task for you, can you add another country name to countries.txt, add, commit, and push please? You'll see that the new commit shows up in the PR right away :) This is to mimic the process of giving/implementing feedback :)

ok done :) @marta-ov

**Review by marta-ov — APPROVED** [review]
Very good! :D
You can merge the PR :)

**Comment by andrii1** [comment]
> Very good! :D You can merge the PR :)

done

**Pull request merged**
